version: '3.9'

services:
  # === PostgreSQL для Auth ===
  VideoHostingAuthDb:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwerty123456!
      POSTGRES_DB: AuthDb
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
        
  # === PostgreSQL для FileService ===
  VideoHostingFileDb:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwerty123456!
      POSTGRES_DB: FileDb
    ports:
      - "5434:5432"
    volumes:
      - file_data:/var/lib/postgresql/data
  
  # === Gateway ===
  gateway.api:
    build:
      dockerfile: VideoHostingApi.Gateway.Web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__AuthDb=Host=VideoHostingAuthDb;Port=5432;Database=AuthDb;Username=postgres;Password=Qwerty123456!
    depends_on:
      - auth.api
      - file.api
  
  # === Auth Service ===
  auth.api:
    build:
      dockerfile: VideoHostingApi.Auth.Web/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AuthDb=Host=VideoHostingAuthDb;Port=5432;Database=AuthDb;Username=postgres;Password=Qwerty123456!
    ports:
      - 8081:8080
    depends_on:
      - VideoHostingAuthDb


    # === File Service ===
  file.api:
    build:
      dockerfile: VideoHostingApi.FileService.Web/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__FileDb=Host=VideoHostingFileDb;Port=5432;Database=FileDb;Username=postgres;Password=Qwerty123456!
      - MINIO_ENDPOINT=VideoHostingS3:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - 8082:8080
    depends_on:
      - VideoHostingS3
      - VideoHostingFileDb

  # === MinIO ===
  VideoHostingS3:
    image: minio/minio:latest
    container_name: VideoHostingS3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  auth_data:
  file_data:
  minio_data:
